# This POD volume is mounted to PD
apiVersion: v1
kind: Pod
metadata:
  name: apppod
spec:
  containers:
  - name: apppod
    image: gcr.io/kubeapps-234209/appshell:1.0
    imagePullPolicy: Always
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ALL
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - name: app-persistent-storage
      mountPath: /home/e-smith/db
      subPath: home/e-smith/db
  volumes:
  - name: app-persistent-storage
    persistentVolumeClaim:
      claimName: app-volumeclaim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-a
  name: app-pv
  selfLink: /api/v1/persistentvolumes/app-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: apppd
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  name: app-volumeclaim
  selfLink: /api/v1/persistentvolumeclaims/app-volumeclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
  volumeName: app-pv
---	  